[package]
name = "sys-info-fetch"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.9.2", package = "gtk4", features = ["v4_16"] }
nvml-wrapper = "0.10.0"
sysinfo = "0.32.0"

[build-dependencies]
glib-build-tools = "0.20.0"
